export type CategoryRule = {
  type: "Despesa" | "Receita";
  fixed: "Fixo" | "Variavel";
  categoryI: string;
  categoryII: string;
  keywords: string[];
};

export const categoryRules: CategoryRule[] = [
  { type: "Despesa", fixed: "Fixo", categoryI: "Assinaturas", categoryII: "Apple iCloud - Vinicius", keywords: ["APPLE.COM/BILL"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Assinaturas", categoryII: "Google One", keywords: ["GOOGLE*GOOGLE ONE -- -9.99", "GOOGLE*GOOGLE ONE", "GOOGLE*GOOGLE ONE "] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Assinaturas", categoryII: "Netflix", keywords: ["NETFLIX"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Assinaturas", categoryII: "Paramount Plus", keywords: ["PARAMOUNT+"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Casa Nova Esting", categoryII: "Financiamento - Esting", keywords: ["7060327031D660501010022518260"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Celular", categoryII: "Celular Family", keywords: ["Kd-Nr.: 6074738889"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Esportes", categoryII: "JJ David", keywords: ["BJJ Ausbildung Dachau", "BJJ EVENT"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Financiamento", categoryII: "Apollo Financiamento - Erica", keywords: ["CC28K3RBB78RKBG6", "Apollo-Optik Holding GmbH ? Co. KG DP25-00125921", "Apollo-Optik Holding GmbH ? Co. KG", "DE52100190001000027873"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Financiamento", categoryII: "Casa Karlsruhe Finanzierung", keywords: ["31440560102023", "31432225842024", "AZ 7545532023", "AZ 7545532014"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Financiamento", categoryII: "Diba", keywords: ["ING-DIBA AG 5328937129"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Financiamento", categoryII: "Diba Rahmenkredit", keywords: ["Rahmenkredit komplett abbezaht", "DE12500105175705720690", "Rahmenkredit", "5705720690.KKRATKR.01.002.142920"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Financiamento", categoryII: "Postbank - Vinao", keywords: ["Darlehensrate 365612957180", "PostBank Kredit--Konto 612957180", "PostBank Kredit -- Konto 612957180"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Esting", categoryII: "Financiamento casa Esting", keywords: ["DARLEHENSABSCHLUSS IBAN DE20701694600020137367", "R + V LEBENSVERSICHERUNG AKTIENGESELLSCHAFT"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Esting", categoryII: "Haus Esting - NK Gründstück", keywords: ["Haushaltsstelle:06001/10000/Steigleder", "AGF Immobilien und Services GmbH"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Karlsruhe", categoryII: "Haus Karlsruhe - Fernwärme", keywords: ["Vertragsnr 250014203", "V 2004774510-BEL400000778120-VK250014203"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Karlsruhe", categoryII: "Haus Karlsruhe - Grundsteuer", keywords: ["501004496409/Grundsteuer"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Karlsruhe", categoryII: "Haus Karlsruhe - Plan B NK", keywords: ["WEG loswohnen II", "loswohnen II , Karlsruhe -- HG Vorauszahlung 302-1-1", "WEG Loswohnen 2", "DE74660501010022518260"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Karlsruhe", categoryII: "Haus Karlsruhe - Wartung Heizung", keywords: ["501004496409/Grundsteuer B 2025"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Karlsruhe", categoryII: "Haus Karlsruhe - Wasser", keywords: ["Vertragskonto 210672822"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Olching", categoryII: "Haus Olching - Internet", keywords: ["933951689"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Olching", categoryII: "Haus Olching - Miete", keywords: ["Schroeder -- Monatsmiete  -- DAUERAUFTRAG", "Schroeder", "Schroeder -- Monatsmiete -- DAUERAUFTRAG"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Olching", categoryII: "Haus Olching - Rundfunk - Taxa TV/Rário ARD", keywords: ["Rundfunk ARD", "bayerischer Rundfunk"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Haus Olching", categoryII: "Haus Olching - Strom", keywords: ["S/836678520540/602712118857", "LichtBlick SE -- Abschlag (Strom)", "VATTENFALL EUROPE SALES", "LichtBlick SE"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Juros Conta negativa", categoryII: "Mensalidade M&M", keywords: ["monatlicher Kartenpreis"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Marketing digital", categoryII: "Active Campaign", keywords: ["EBN    *ACTIVECAMP -- -9.92", "ACTIVECAMP"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Marketing digital", categoryII: "ChatGPT", keywords: ["OPENAI *CHATGPT SUBSCR"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Projeto social", categoryII: "BOG Mitglied", keywords: ["Mitgliedsbeitrag 2024 f r Erica und Vinicius Steiglede", "Bruederlichkeit ohne Grenzen e.V.--Mitgliedsbeitrag 2025", "Bruederlichkeit ohne Grenzen e.V. -- Mitgliedsbeitrag", "PAYPAL *BRUEDERLICH     4029357733"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Seguros", categoryII: "DEVK Vinao", keywords: ["6134367652"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Seguros", categoryII: "Seguros - DEVK", keywords: ["Z00013153275 Leben", "Haushaltglas", "Hausrat", "Haftpflicht", "Rechtsschutz", "622026799196", "DEVK Riehlerstrasse 190 Koeln", "DE87370605900000402702", "DEVK Lebensversicherungsverein"] },
  { type: "Despesa", fixed: "Fixo", categoryI: "Taxas", categoryII: "Amex - ExtraPunkte Payback", keywords: ["Amex - ExtraPunkte Teilnahmegebuehr"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Amazom", categoryII: "AMAZOM", keywords: ["AMAZON", "AMZN", "AMZ*"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Assinaturas", categoryII: "Amazon Prime", keywords: ["AMZNPrime"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Assinaturas", categoryII: "Audiable", keywords: ["AUDIBLE GMBH"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Bosch Almoco", categoryII: "Amoco Vinicius", keywords: ["FRUCHTWERK E.K."] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Bosch Viagem", categoryII: "Team-Event", keywords: ["Banca Prealpi Sanbiagio Credito Cooperativo "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Carros", categoryII: "Carro - Posto de gasolina", keywords: ["Tankstelle", "ALLGUTH"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Carros", categoryII: "Carro Mercedes - Imposto", keywords: ["FFB FA 317 KFZ-Steuer"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Carros", categoryII: "Carro Mercedes - Seguro", keywords: ["Kfz-Versicherung Nr 870711522 fuerIhr Fahrzeug mit dem Kennzeichen FFB FA 317", "KFZ0047667216"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Carros", categoryII: "Multa de transito", keywords: ["Stadt Mannheim "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Compras casa", categoryII: "Decoracao", keywords: ["JYSK SE"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Compras casa", categoryII: "eletrodomesticos", keywords: ["Saturn", "Mediamarkt"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Compras casa", categoryII: "moveis", keywords: ["idea", "MOEMAX"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Compras casa", categoryII: "Tedi", keywords: ["TEDI"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Cuidados pessoais", categoryII: "Esterica - produtos - Erica", keywords: ["Silvia Griebl", "L'OCCITANE DÜSSELDORF"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Cuidados pessoais", categoryII: "Limpeza de pele", keywords: ["natalia.fertsc"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Despesas Não Classificadas", categoryII: "### Gutschein ###", keywords: ["SP WUNSCHGUTSCHEIN D"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Educacao", categoryII: "Gymnasium Olching ", keywords: ["Gymnasium Olching "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Educacao", categoryII: "Livros Diogo", keywords: ["DANKE DER BUCHLADEN"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Educacao", categoryII: "Online Schülerhilfe", keywords: ["SCHULHILFEV"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Cademia Diogo", keywords: ["OLC--0157-0000631 OLC-2637639", "OLC-2637639"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Cademia Erica", keywords: ["OLC--0157-0000373 OLC-2428106 RED LABEL", "OLC-2428106 RED LABEL"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Cademia Vinicius", keywords: ["OLC--0156-0000276 OLC-2637461 RED LABEL", "OLC-2637461 RED LABEL"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Schwimm Verein", keywords: ["SV Fuerstenfeldbrucker Wasserratten e.V. "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Tennis Kids", keywords: ["Georgi Kranchev", "Tanja Mayr"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Esportes", categoryII: "Tennis Verein", keywords: ["Tennisclub Edelweiss Groebenzell e.V. "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Ferias", categoryII: "Ferias Londres", keywords: ["THISTLEMARBLE LONDON", "Flugstrecke:Von: MEMMINGEN Nach: LONDON", "ENGLAND UK Fluglinie:", "WARNER BROS WARNER BROS UNITED KINGDOM"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Ferias", categoryII: "Ferias Transferencia para Brasil", keywords: ["WESTERN UNION--e-commerce", "WESTERN UNION", "Wise", "Marilia Duarte Viana "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Ferias", categoryII: "Ferias Vista Cassius", keywords: ["Wolfsschlucht Pruem mbH"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Haus Olching", categoryII: "Haus Olching - Manutenção Casa", keywords: ["DANKE BZO OLCHING GMBH"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Higiene pessoal", categoryII: "DM", keywords: ["DM Drogerie", "DM-DROGERIE MARKT"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Higiene pessoal", categoryII: "Müller", keywords: ["MUELLER MH HANDELS GMB", "MUeLLER OLCHING 1-1 E", "MUELLER 1500"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Higiene pessoal", categoryII: "Rossmann", keywords: ["rossmann"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Juros Conta negativa", categoryII: "Juros Amex", keywords: ["ZINSBELASTUNG"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Juros Conta negativa", categoryII: "Juros M&M", keywords: ["1,95% für Währungsumrechn"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Juros Conta negativa", categoryII: "Juros Sparkasse", keywords: ["ABSCHLUSS -- 0000000000 -- Sparkasse"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Carros", categoryII: "Carro - estacionamento", keywords: ["Parkhaus", "HandyParken Muenchen", "Parkgaragen", "PBW PG KRIEGSBERGSTR.", "Parkgarage", "PARKEN OLYMPIA"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Lazer", categoryII: "Alugar Video", keywords: ["Prime Video"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Lazer", categoryII: "Jogos - David", keywords: ["ROBLOX.COM 18888582569  SAN MATEO"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Lazer", categoryII: "Oktoberfest", keywords: ["Oktoberfest"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Restaurante", categoryII: "Restaurante", keywords: ["McDonalds", "Pablo Emilio Burger", "PIZZA HUT", "Ristorante Da Umberto", "Eiscafe Dolomiti", "Belmondo", "Hans im Tal", "HEINRITZI GMBH & CO.", "BOTECO BRAZILIAN RESTAU NUERNBERG", "ABACCOS STEAKHOUSE", "DING TEA                MUENCHEN", "I LOVE LEO GMBH&CO", "Weintreff Zom Hasatanz", "RESTAURANT", "KatNi Asia"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Mercado ", categoryII: "Mercado Edeka", keywords: ["EDEKA"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Mercado ", categoryII: "Mercado Lidl / Aldi", keywords: ["ALDI", "LIDL"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Mercado ", categoryII: "Mercado Netto", keywords: ["NETTO"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Mercado ", categoryII: "Mercado Outros", keywords: ["MADE IN PORTUGAL//MUENCHEN/DE", "Norma", "Asia Markt"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Mercado ", categoryII: "Mercado Rewe", keywords: ["REWE"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Padaria", categoryII: "Padaria", keywords: ["Backstube", "baeckerei", "Ihle", "*Baeckerei Wuen", "Rischarts Backhau", "UZR*Backzeit AKD GmbH", "Backzeit", "WUENSCHE BERGKIRCHEN"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Pagamento Cartao fechamento", categoryII: "Amex pagamento", keywords: ["pagamento Amex", "AMERICAN EXPRESS", "Amex - RETOURNIERTE LASTSCHRIFT", "Amex - ZAHLUNG ERHALTEN. BESTEN DANK."] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Pagamento Cartao fechamento", categoryII: "M&M pagamento", keywords: ["pagamento M&M", "DEUTSCHE KREDITBANK AKTIENGESELLSCHAFT"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Pagamento Cartao fechamento", categoryII: "Sparkasse pagamento", keywords: ["pagamento Sparkasse", "pagamento cartao de credito Amex"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Pets", categoryII: "Comida Annie", keywords: ["www.futalis.de", "Fressnapf"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Presentes e festas", categoryII: "Festa de Aniver David", keywords: ["UZR*FunZone"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Viajem Bosch", categoryII: "Viajem Bosch - Vinicius", keywords: ["Viajem Bosch", "GAUCHO STEAKHOUSE", "DETROIT NOVI", "HERTZ CAR"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Roupas", categoryII: "Roupas David", keywords: ["C&A", "HENNES & MAURITZ", "C & A Mode GmbH & Co."] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Roupas", categoryII: "Roupas Diogo", keywords: ["HOLLISTER CO OLYMPIA HA MUNICH BY", "FABRIC                  MUENCHEN", "HOLLISTER "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Roupas", categoryII: "Roupas geral", keywords: ["ZALANDO", "DECATHLON", "ABOUT YOU", "HM.COM                  HAMBURG", "DEICHMANN SE 1129       GROEBENZELL", "Zara", "H&M", "DECATHLON Deutschland "] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saque dinheiro", categoryII: "Saque dinheiro - Sparkasse", keywords: ["BARGELDAUSZAHLUNG -- DE66700530709000481409", "GELDAUTOMAT", "BARGELDAUSZAHLUNG"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Dentista", keywords: ["Gemeinschaftspraxis fuer Kinderzahnheilkunde", "Zahnarztpraxis"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Farmacia", keywords: ["Apotheke"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Laboratorio", keywords: ["Labor Augsburg MVZ"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Logo David", keywords: ["Marion Schanz"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Medico", keywords: ["PVS bayern GmbH", "Gemeinschaftspraxis Dres. Huber Neu//MARKT SCHWABEN/DE", "Hautarztpraxis Dr Poppe"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Medico ADHS Vinicius", keywords: ["Neuy-Lobkowicz"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Oculos David", keywords: ["APOLLO OPTIK -- -40 -- Processed", "OLCHING -- APOLLO-OPTIK"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Saude", categoryII: "Palmilha", keywords: ["AGM MUELLER GMBH"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Seguros", categoryII: "AOK Seguro Vinao", keywords: ["OB-D400492027"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Taxas", categoryII: "Taxa Banco Sparkasse", keywords: ["ENTGELTABSCHLUSS"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Temu", categoryII: "Temu", keywords: ["TEMU.COM                DUBLIN 2"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Transferencia Dinheiro Brasil", categoryII: "Transferencia Brasil", keywords: ["TransferWise"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Transporte", categoryII: "Transporte - Vinicius - trabalho", keywords: ["MVV TICKETSHOP LOGPAY"] },
  { type: "Despesa", fixed: "Variavel", categoryI: "Transporte", categoryII: "Transporte familia", keywords: ["VOI DE"] },
  { type: "Receita", fixed: "Fixo", categoryI: "Haus Knielingen", categoryII: "Haus Karlsruhe Miete", keywords: ["Miete incl. Nebenkosten"] },
  { type: "Receita", fixed: "Fixo", categoryI: "Kindergeld", categoryII: "Kindergeld", keywords: ["Arbeit - Familien kasse", "Bundesagentur"] },
  { type: "Receita", fixed: "Fixo", categoryI: "SALARIO", categoryII: "Salario Vinicius", keywords: ["Entgelt 71336818"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Financiamento", categoryII: "Financiamento dividas Targobank", keywords: ["00007285400453 VINICIUS STEIGLEDER VIELEN DANK IHRE TARGOBANK "] },
  { type: "Receita", fixed: "Variavel", categoryI: "SALARIO", categoryII: "Salario Erica", keywords: ["Emylie Maria Bernardes Pereira", "Rogerio Behr", "Ricardo Nuber", "David Brandao Da Silva", "Fernanda Mendonca Finato", "Leonardo Morassi Capitanio"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Steuererklärung", categoryII: "Steuererklärung", keywords: ["Finanzamt Fuerstenfeldbruck Finanzkasse"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Trabalho Erica", categoryII: "Andressa Vilas Boas Nogueira Lima", keywords: ["Andressa Vilas Boas Nogueira Lima"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Trabalho Erica", categoryII: "Bianca De Freitas Lima", keywords: ["Bianca De Freitas Lima", "biancaflima"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Trabalho Erica", categoryII: "Flavia Frattini ", keywords: ["Dr. Marco Rocha Curado", "Flavia Frattini "] },
  { type: "Receita", fixed: "Variavel", categoryI: "Trabalho Erica", categoryII: "Marcelo Guida Tavares", keywords: ["Marcelo Guida Tavares", "Bettina Tavares "] },
  { type: "Receita", fixed: "Variavel", categoryI: "Trabalho Erica", categoryII: "Marilia Duarte Viana", keywords: ["Marilia Duarte Viana"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Vendas online", categoryII: "Vendas online", keywords: ["Mangopay", "Kleinanzeigen"] },
  { type: "Receita", fixed: "Variavel", categoryI: "Viajem Bosch", categoryII: "Reembolso Bosch", keywords: ["Bosch GmbHTvl Exp"] },
];

export const normalizeText = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, " ")
    .trim();
